version: "3.9"

services:

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres_db
